# Generated by Django 4.1.3 on 2022-11-26 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='favorites',
            field=models.ManyToManyField(related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='в избранных'),
        ),
    ]
